// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdxxbsnienjuyyjrduwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkeHhic25pZW5qdXl5anJkdXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2ODY4NjQsImV4cCI6MjA1MDI2Mjg2NH0.5Boq90DGy21xxGLsYp0l3wuqBO27bpRJbbZ8UbXKpzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);